import Button from '@/components/button';
import GitHubIcon from '@/components/icons/github';
import Layout from '@/components/layout';
import {loginWithGiHub, onAuthStateChanged} from '@/firebase/client';
import {colors} from '@/styles/theme';
import {Inter} from '@next/font/google';
import Head from 'next/head';
import {useEffect, useState} from 'react';

const inter = Inter({subsets: ['latin']});

export default function Home() {
  const [user, setUser] = useState<any>(undefined);

  const handleClick = async () => {
    await loginWithGiHub();
  };

  useEffect(() => {
    onAuthStateChanged((user: any) => setUser(user));
  }, []);

  return (
    <>
      <Head>
        <title>TwitDev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <section>
          <img src="/logo.png" alt="Logo" />
          <h1>TwitDev</h1>
          <h2>Talk about development with developers</h2>
          <div>
            {user === null && (
              <Button onClick={handleClick}>
                <div className="button-content">
                  <GitHubIcon fill="white" width={24} height={24} />
                  Login with Github
                </div>
              </Button>
            )}
            {user && user.avatar && (
              <div>
                <img src={user.avatar} alt="User Avatar" />
                <strong>{user.username}</strong>
              </div>
            )}
          </div>
        </section>
      </Layout>

      <style jsx>{`
        section {
          display: grid;
          height: 100%;
          place-content: center;
          place-items: center;
        }
        img {
          width: 120px;
        }
        h1 {
          color: ${colors.secondary};
          font-weight: 800;
          margin-bottom: 16px;
        }
        h2 {
          color: ${colors.primary};
          font-size: 21px;
          margin: 0;
        }
        div {
          margin-top: 16px;
        }
        .button-content {
          display: flex;
          align-items: center;
          margin: 0;
        }
        .button-content > :global(svg) {
          margin-right: 8px;
        }
      `}</style>
    </>
  );
}
